version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
      # - ./db/:/my/sqlite/path/
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./db/:/root/db/
    