"""empty message

Revision ID: fd08f83c92c1
Revises: 
Create Date: 2022-02-04 16:14:09.606241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd08f83c92c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('kcals_per_rep', sa.Integer(), nullable=True),
    sa.Column('type_of_exercise', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('trainings',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('training_id')
    )
    op.create_table('trainings_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('repeats', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.training_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings_exercises')
    op.drop_table('trainings')
    op.drop_table('exercises')
    # ### end Alembic commands ###
